### PR TITLE
feat(search-modal): add search modal

### PR DESCRIPTION
**Pull request by anggidast**

### CODE REVIEW

**Review by wildanbudi — APPROVED** [review]

**Review by nurulputri — APPROVED** [review]
all ok

**Comment by anggidast** [comment]
ready to re-review @wildanbudi @nurulputri

**Comment by wildanbudi** [comment]
have some conflict on this branch @anggidast

**Review by wildanbudi — APPROVED** [review]
LGTM

**Review by wildanbudi — APPROVED** [review]

**Comment by anggidast** [comment]
try to checkout this branch on your local machine (pull) and check the navigation functionality @wildanbudi

**Comment by wildanbudi** [comment]
the navigation hasn't work, may need to merge with latest update from navigation branch #12 @anggidast

**Review by nurulputri — APPROVED** [review]

**Comment by wildanbudi** [comment]
> the navigation hasn't work, may need to merge with latest update from navigation branch #12 @anggidast

working, forgot to perform git pull

**Pull request merged**
